# Generated by Django 4.1.1 on 2022-11-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_banner_tiendaatributo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1. Banners'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': '2. Categorias'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': '3. Marcas'},
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name_plural': '4. Tiendas'},
        ),
        migrations.AlterModelOptions(
            name='tiendaatributo',
            options={'verbose_name_plural': '5. Atributos tiendas'},
        ),
        migrations.AddField(
            model_name='tienda',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='image',
            field=models.ImageField(upload_to='tienda_imgs/'),
        ),
    ]
