# Generated by Django 4.1.1 on 2022-11-05 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_banner_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='is_featured',
            new_name='es_destacado',
        ),
    ]
